---
name: WWW-Rafb-Retrieve
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: retrieve pastes from http://rafb.net/paste/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  HTML::Entities: 1.35
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  URI: 1.35
build_requires:
  Test::More: 0
provides:
  WWW::Rafb::Retrieve:
    file: lib/WWW/Rafb/Retrieve.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
